update plurios-live

diff --git a/plurios-live b/plurios-live
--- a/plurios-live
+++ b/plurios-live
@@ -7,20 +7,10 @@ set -o pipefail         # exit on pipeline error
 set -u                  # treat unset variable as error
 
 # === variables ===
-
 SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
+CONF_VAR="config/variables.conf"
 
-LIB_PLURIOS="lib/plurioslib"
-
-CONF_PLURIOS="config/plurios.conf"
-CONF_CALAMARES="config/core/calamares.conf"
-CONF_PREPARE_ISO="config/prepare-iso-live/prepare"
-CONF_DOTFILES="config/dotfiles"
-DIR_CONF_PLURIOS="config/plurios"
-DIR_CONF_IMAGE="config/image"
-DIR_CONF_CALAMARES="config/custom/calamares"
-#BOOT_ISOLINUX_PLURIOS="config/core/live.cfg"
-#BOOT_GRUB_PLURIOS="config/core/grub.cfg"
+. $CONF_VAR || exit 1
 
 # === variables workspace ===
 WORKSPACE="workspace"
@@ -53,6 +43,11 @@ fi
 
 
 ISO_FILE=$1
+if ! [[ -n "$ISO_FILE" && -f "$ISO_FILE" && "${ISO_FILE##*.}" == "iso" ]]
+then
+    echo "Error: Use an existing file and it is in ISO format"
+fi
+
 echo "start: $(date)"
 run
 echo "end: $(date)"
